name: publish to nuget

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish jx.dcsoup
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: jx.dcsoup/jx.dcsoup.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
